@startuml c1
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LANDSCAPE()

Person(user, "Developer", "needs to verify their configurations")
System_Boundary(extension, "ConfigMate VS Code Extension") {
	System(configmate, "ConfigMate")
	System(gui, "GUI")
	Container(cli, "CLI")
}

Rel(user, extension, "Installs", "HTTPS")
Rel_R(user, gui, "Uses", "VS Code\nActivity Bar")
Rel_R(user, cli, "Uses", "VS Code\nTerminal")
Rel_D(gui, cli, "Uses")
Rel_D(configmate, cli, "Provides")

' SHOW_FLOATING_LEGEND()

@enduml