@startuml c4
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LANDSCAPE()

' Person(user, "User", "Uses ConfigMate to manage config files")

System_Boundary(extension, "ConfigMate VS Code Extension") {
	System_Boundary(gui, "GUI [Activity Bar]") {
		Container(specFiles, "specFiles View", "TypeScript, VS Code API", "Graphical file manager for .specFile files (.json, .toml, .hocon)")
		Container(configFiles, "Config Files View", "TypeScript, VS Code API", "Graphical file manager for config files specified in selected specFile(s)")
	}
	Container(configmateProvider, "ConfigMate Provider", "TypeScript", "Runs the ConfigMate server, then routes API requests & responses appropriately")
	Container(diagnosticsProvider, "Diagnostics Provider", "TypeScript, VS Code API", "Uses error data in response to add in-editor feedback & helpful diagnostic information")
	System_Boundary(configmate, "ConfigMate") {
		Container(cli, "CLI", "GoLang", "Provides command-line interaction with the ConfigMate program")
		Container(analyzer, "Analyzer", "GoLang", "Uses Parsers to apply rules, evaluate checks, & produce error information")
		Container(parser, "Parser", "GoLang", "Parses config files depending on their type into a common format for the Analyzer")
		Container(server, "Server", "GoLang", "Provides a JSON API for the GUI to interact with")
	}
}
Rel_R(configmateProvider, server, " ")
Rel_L(server, configmateProvider, " ")
Rel_D(configmateProvider, diagnosticsProvider, " ")

Rel_R(specFiles, configmateProvider, " ")
Rel_R(configFiles, configmateProvider, " ")
Rel_L(diagnosticsProvider, specFiles, " ")
Rel_L(diagnosticsProvider, configFiles, " ")

Rel_D(cli, analyzer, " ")
Rel_L(analyzer, cli, " ")
Rel_R(server, analyzer, " ")
Rel_L(analyzer, server, " ")
Rel_D(analyzer, parser, " ")
Rel_U(parser, analyzer, " ")

' SHOW_FLOATING_LEGEND()
@enduml
