@startuml c4
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LANDSCAPE()

Person(user, "Developer", "needs to verify their configurations")
System_Boundary(extension, "VS Code Extension") {
	System_Boundary(gui, "Activity Bar") {
		Container(rulebooks, "Rulebooks", "TypeScript,\nVS Code TreeDataProvider API", "Graphical file manager for .rulebook files")
		Container(configFiles, "Config Files", "TypeScript,\nVS Code TreeDataProvider API", "Graphical file manager for config files (.json, .yml, ...)")
	}
	Container(configmateProvider, "ConfigMate Provider", "TypeScript", "Translates GUI interactions into CLI commands")
	Container(diagnosticsProvider, "Diagnostics Provider", "TypeScript", "Provides error highlighting & helpful diagnostic information")
	System_Boundary(configmate, "ConfigMate") {
		Container(cli, "CLI", "GoLang", "Provides command-line interaction with the ConfigMate program")
		Container(analyzer, "Analyzer", "GoLang", "Coordinates files, rules, and parsers")
		Container(parser, "Parser", "GoLang", "Applies rules against files")
		Container(server, "Server", "GoLang", "Provides up-to-date rule verification")
	}
}
Rel(user, extension, "Installs", "VS Code Marketplace\nor Extensions Tab")
Rel(user, gui, "Uses", "VS Code GUI")
Rel(user, cli, "Uses", "VS Code Terminal")

Rel_L(configmateProvider, cli, "Uses")
Rel_U(configmateProvider, rulebooks, "Provides")
Rel_U(configmateProvider, configFiles, "Provides")

Rel_U(configmateProvider, diagnosticsProvider, "Provides")
Rel_L(diagnosticsProvider, rulebooks, "Provides")
Rel_L(diagnosticsProvider, configFiles, "Provides")

Rel(cli, analyzer, "Uses")
Rel_U(analyzer, parser, "Uses")
Rel_L(analyzer, server, "Uses")

SHOW_FLOATING_LEGEND()
@enduml
