@startuml c4
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LANDSCAPE()

' Person(user, "User", "Uses ConfigMate to manage config files")

System_Boundary(extension, "ConfigMate VS Code Extension") {
	System_Boundary(gui, "GUI [Activity Bar]") {
		Container(rulebooks, "Rulebooks View", "TypeScript, VS Code API", "Graphical file manager\nfor .rulebook files\n(.json, .toml, .hocon)")
		Container(configFiles, "Config Files View", "TypeScript, VS Code API", "Graphical file manager\nfor config files specified\nin selected rulebook(s)")
	}
	Container(configmateProvider, "ConfigMate Provider", "TypeScript", "Runs the ConfigMate server, then routes API requests & responses appropriately")
	Container(diagnosticsProvider, "Diagnostics Provider", "TypeScript, VS Code API", "Uses error data in response to add in-editor highlighting & diagnostic information")
	System(configmate, "ConfigMate")
}
Rel_U(configmateProvider, configmate, "\nRequest", "HTTPS/\nJSON")
Rel_D(configmate, configmateProvider, "\nResponse", "HTTPS/\nJSON")
Rel_U(configmateProvider, diagnosticsProvider, "Response", "JSON")

Rel_R(rulebooks, configmateProvider, "Request", "VS Code\nCommand")
Rel_R(configFiles, configmateProvider, "Request", "VS Code\nCommand")
Rel_L(diagnosticsProvider, rulebooks, "Response", "JSON")
Rel_L(diagnosticsProvider, configFiles, "Response", "JSON")

' SHOW_FLOATING_LEGEND()
@enduml
