@startuml c4
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title ConfigMate VS Code Extension

Person(user, "Developer", "needs to verify their configurations")
System(configmate, "ConfigMate")
Container(gui, "GUI")
System(extension, "VS Code Extension")
Container(cli, "CLI")

Rel_R(user, extension, "Installs", "HTTPS")
Rel_R(user, gui, "Uses", "HTTPS")
Rel_R(user, cli, "Uses", "HTTPS")
Rel_R(extension, configmate, "Uses", "HTTPS")
Rel_U(extension, gui, "Provides")
Rel_U(configmate, cli, "Provides")

SHOW_FLOATING_LEGEND()

@enduml