name: Check buildability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Clone, Build, Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone GUI
        uses: actions/checkout@v4.0.0

      - name: Clone CLI
        uses: actions/checkout@master
        with:
          repository: ConfigMate/ConfigMate
          path: configmate

      - name: Set up npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Install dependencies
        run: npm install && npm install -g @vscode/vsce

      - name: Build GUI
        run: npm run compile

      - name: Build CLI
        run: npm run build-server

      - name: Run server      
        run: npm run server

      - name: Deploy
        run: vsce publish -p ${{ secrets.AZURE_ACCESS_TOKEN }} patch --no-git-tag-version
