name: Check buildability

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Build & Package Extension
    runs-on: ubuntu-latest

    steps:
      - name: Clone CLI
        uses: actions/checkout@master
        with:
          repository: ConfigMate/ConfigMate
          path: configmate

      - name: Clone extension
        uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Set up npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: Build CLI
        run: npm run build-server

      - name: Install extension dependencies
        run: npm install && npm install -g @vscode/vsce

      - name: Compile and package extension
        run: vsce package
