name: Clone & Build CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          name: ConfigMate/ConfigMate
          ref: refs/heads/release

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Build
        run: make configm
