name: Clone & Build CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  configmate:
    name: Clone
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          repository: ConfigMate/ConfigMate

      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Build
        run: make configm
