name: Clone, Build, Deploy

on:
  push:
    branches:
      - main
      - cli-integration
  pull_request:
    branches:
      - main

jobs:
  configmate:
    name: Set up CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bin

    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          repository: ConfigMate/ConfigMate

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Set up Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 8

      - name: Set up npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: Build
        run: npm run make

  gui:
    name: Set up GUI
    runs-on: ubuntu-latest

    steps:
      - name: Set up npm
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run compile
