name: Clone & Build CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  configmate:
    name: Setup ConfigMate CLI
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@master
        with:
          repository: ConfigMate/ConfigMate

      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.19

      - name: Generate parsers
        run: make generate_parsers

      - name: Setup Mocks
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
          make mocks

      - name: Build
        run: go build ./...
